### ISSUE TITLE
Required esModuleInterop in true for TypeScript projects

### ISSUE THREAD

**Issue by itPiligrim** [winkjs/wink-nlp#105]
Please add to documentation, that TypeScript project required esModuleInterop in true to import wink-nlp module.
See: https://www.typescriptlang.org/tsconfig#esModuleInterop
It's not obvious fo full TypeScript libs.

Your project is cool. 🥇

**Comment by sanjayaksaxena** [comment]
@itPiligrim 

Many thanks for your input. Please consider updating the README and send a PR — in fact we need contributions in this area. The existing type definitions are also result of @pimpale efforts and contributions.

We are delighted to know that you found winkNLP useful.

Best,
Sanjaya

**Comment by sanjayaksaxena** [comment]
Thank you for your contibution @itPiligrim 👍
