### ISSUE TITLE
what is the default behaviour of `learnCustomEntities`?

### ISSUE THREAD

**Issue by bboyle** [winkjs/wink-nlp#111]
I had a lot of trouble using learnCustomEntities until I discovered the second config parameter with its `usePos: true` setting. 

![image](https://user-images.githubusercontent.com/559114/214218841-6c6ac333-427c-42df-b4bb-d365a1e503a6.png)
https://winkjs.org/wink-nlp/learn-custom-entities.html

1. `matchValue` - the docs show that both true and false are the default. Something is not right there.

2. `usePos` - The docs say usePos defaults to true, but does it actually default to false? I was not able to match `NOUN` until I explicitly used the config `usePos: true`. I think the default is false. In either case, can we also document the config options on the learn custom entities page here? I was very confused following these examples:  https://winkjs.org/wink-nlp/custom-entities.html (I actually stumbled across the config options in the source code rather than reading about it in the docs)

Custom entities are a great feature, be great to make it easier to understand how to use them. Thanks :)

**Comment by sanjayaksaxena** [comment]
Thanks for sending the PR.
