### ISSUE TITLE
PoS markup example on website does not work with typescript

### ISSUE THREAD

**Issue by boompig** [winkjs/wink-nlp#113]
On this webpage: https://winkjs.org/wink-nlp/wink-nlp-in-browsers.html

There is this code:

```
const winkNLP = require( 'wink-nlp' );
const model = require( 'wink-eng-lite-web-model' );
const nlp = winkNLP( model )
// Acquire "its" and "as" helpers from nlp.
const its = nlp.its;
const as = nlp.as;

const text = `Its quarterly profits jumped 76% to $1.13 billion for the three months to December, from $639million of previous year.`;
const doc = nlp.readDoc( text );

doc.entities().each((e) => e.markup());
document.getElementById("result").innerHTML = doc.out(its.markedUpText);
```

I've adapted it to typescript to get the following:

```
import winkNLP from 'wink-nlp';
import model from 'wink-eng-lite-web-model';
const nlp = winkNLP( model )
// Acquire "its" and "as" helpers from nlp.
const its = nlp.its;
const as = nlp.as;

const text = `Its quarterly profits jumped 76% to $1.13 billion for the three months to December, from $639million of previous year.`;
const doc = nlp.readDoc( text );

doc.entities().each((e) => e.markup());
(document.getElementById("result") as HTMLElement).innerHTML = doc.out(its.markedUpText);
```

And I am seeing this error:

```
(method) ItemEntity.markup(beginMarker: string, endMarker: string): void
Expected 2 arguments, but got 0.ts(2554)
index.d.ts(186, 12): An argument for 'beginMarker' was not provided.
```

Is it possible the typescript definition of `ItemEntity.markup` isn't quite correct? When I run the code in nodejs without typescript, everything runs just fine.

**Comment by sanjayaksaxena** [comment]
@boompig Thanks for highlighting. You are right the type declaration for markup is `markup(beginMarker: string, endMarker: string): void;`. For the time being, request you to supply these values — JS default values are `'<mark>'` and `'</mark>'` respectively.

Would appreciate if you could consider contributing to the project by fixing the [declaration](https://github.com/winkjs/wink-nlp/blob/5d913ab11b7abc6060d69b4f57652b282fb9314d/types/index.d.ts#L157).
