### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by LukeGT** [winkjs/wink-nlp#12]
Are there any plans to write Typescript declarations files for the wink modules? I use Typescript for all JS projects these days, and in order to use wink properly I've had to hack up some declaration files (I know there's the `any` type, but ew).

I'd be happy to contribute what I've written so far, but I can't promise it's complete or correct. It has been serving me well so far though :)

**Comment by sanjayaksaxena** [comment]
It will be great if you could contribute. We are not into Typescript, but we will fully support you in this endeavor. Let us discuss possibilities!

**Comment by sanjayaksaxena** [comment]
@LukeGT closing the issue for now, lets reopen whenever you are ready.
