### ISSUE TITLE
typescript definitions not found

### ISSUE THREAD

**Issue by rawsh** [winkjs/wink-nlp#121]
Hello,

I'm getting the following linting errors in nextjs:

```
'BM25VectorizerConfig' is declared but its value is never read.ts(6133)
Could not find a declaration file for module 'wink-nlp/utilities/bm25-vectorizer'. '/home/robert/Documents/dank-edge/node_modules/.pnpm/wink-nlp@1.14.0/node_modules/wink-nlp/utilities/bm25-vectorizer.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/wink-nlp` if it exists or add a new declaration (.d.ts) file containing `declare module 'wink-nlp/utilities/bm25-vectorizer';`
```

I see that the types for wink-nlp/utilities/bm25-vectorizer exist but for some reason they are not getting picked up. I have 

```
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
```

In my typescript config.

Edit: it looks like a workaround is importing winknlp first, even though I'm not using it.

```
import winkNLP from "wink-nlp";
import BM25VectorizerConfig from "wink-nlp/utilities/bm25-vectorizer";
```

**Comment by rachnachakraborty** [comment]
Hi @rawsh 

The bm25-vectorizer has a dependency on wink-nlp. 

Best,
Rachna

**Comment by rawsh** [comment]
@rachnachakraborty Gotchu, thanks. Unrelated but I can't get its.modelJson to work for the life of me.

```typescript
chunks.forEach((chunk: any) => bm25.learn(nlp.readDoc(chunk.text).tokens().out(its.normal) as unknown as Tokens));
console.log(bm25.out(its.modelJson))
// [{}]
```

**Comment by rachnachakraborty** [comment]
**@rawsh** Thanks for your contribution. 

The PR has been merged and new version released.

Best,
Rachna
