### ISSUE TITLE
Typescript imports don't work correctly

### ISSUE THREAD

**Issue by robertleeplummerjr** [winkjs/wink-nlp#125]
I seem to only be able to import with the following:
```ts
import * as winkNlp from "wink-nlp";
import * as winkEngLiteWebModel from "wink-eng-lite-web-model";
const nlp = winkNlp(winkEngLiteWebModel); // throws: TS2349: This expression is not callable.
```

Side note: It would really help if your documentation didn't jump to the conclusion you've already imported and setup wink-nlp.

**Comment by itPiligrim** [comment]
See docs for tsconfig.json: https://github.com/winkjs/wink-nlp#how-to-configure-typescript-project

My example:

`import winkNLP, {
    Document as WinkDocument,
    PartOfSpeech,
    ItemSentence,
} from "wink-nlp";
import model from "wink-eng-lite-web-model";

const nlp = winkNLP(model);




`
