### ISSUE TITLE
Named-Entity Recognition and Proper Nouns? 

### ISSUE THREAD

**Issue by ShaneOH** [winkjs/wink-nlp#127]
Hey all, 

Firstly this is an amazing library, thank you for doing such great work. 

I have two separate but related questions/comments:

1. How does named-entity recognition work (not custom)? From reading the docs, it looks like it's supposed to work out of the box with the `ner` pipeline and then printing out `.entities()`. However this seems to only support the following: `date, ordinal, cardinal, money, percent, time, duration, hashtag, emoji, emoticon, email, url and mention`. This is well-documented, but I was surprised to find it didn't support tagging e.g. Person or Organization names, where NER has a lot of value. As-is, I can't use the `ner` pipeline since I'm really only looking to filter out Proper Nouns/Names, which I'd imagine is a common use-case. Is this on the roadmap for future support, or is there something I'm missing here?

I would expect to be able to parse out a sentence "John Doe and Susan Smith work at Coca-Cola" and see three (five?) entitles in that sentence. Instead there are none.

2. On the subject of proper nouns, the implementation seems to naively tag the first word of most sentences as a proper noun (unless it's overruled by another specific part-of-speech), only because it's capitalized. Some examples I've found from just cursory testing:

```
Sentence is:  Main menu
Tokens:  (2) ['PROPN', 'NOUN']
```

```
Sentence is:  Contents
Tokens:  ['PROPN']
```

```
Sentence is:  Current events
Tokens:  (2) ['PROPN', 'NOUN']
```

```
Sentence is:  Following Vogel's firing after the season, he said, "I'm not sure what his issue was with me."
Tokens:  (23) ['PROPN', 'PROPN', 'PART', 'NOUN' ...
```

```
Sentence is:  Fourth triple-double season and career triple-doubles record
Tokens:  (11) ['PROPN', 'ADJ', 'PUNCT', 'ADJ', 'NOUN', ...
```

I can simply guard against this in my own code of course, but it does seem like something that can be improved in the model. Looking forward to hearing your take on this feedback! 

(For context, I'm using `wink-eng-lite-web-model`)

**Comment by rachnachakraborty** [comment]
Hi @ShaneOH 

Thank you so much for highlighting the issue with a detailed analysis. It appears to be a miss, which we are digging deeper and hope to fix it soon.

Shall keep you posted.

Thanks once again for your contribution.

Best,
Rachna

**Comment by rachnachakraborty** [comment]
Hi  @ShaneOH

1. Your observation is correct — we currently do not support ORG & PERSON entities. It is definitely there on our ROADMAP of model.
2. Regarding incorrect pos tagging, request you to kindly share the specific versions of wink-nlp & wink-eng-lite-web-model in use along with the code snippet that produced these tags.
3. We are not able to recreate the exact outcome as shared by you. Here are few snapshots of testing on Runkit.

![telegram-cloud-photo-size-5-6262816024655150465-x](https://github.com/winkjs/wink-nlp/assets/45709/c194e9e7-f55a-4c62-ad2b-1b6897a4bd91)
![telegram-cloud-photo-size-5-6262816024655150466-x](https://github.com/winkjs/wink-nlp/assets/45709/b8f4e031-0326-4a1f-b56c-7c655f6e4733)

Best,
Rachna
