### ISSUE TITLE
Creating Special Entities

### ISSUE THREAD

**Issue by markhoney** [winkjs/wink-nlp#130]
I'd like to manually create Special Entities in my text, based on matching a string, but there doesn't seem to be a way to use a custom function to do this. So, instead, I'm creating patterns that contain the strings I'm looking for, then training the model with these strings before loading the text.

Weirdly, some of my patterns are causing the following error:

        if ( fsm[ state ][ otherwise ] ) {
                         ^

TypeError: Cannot read properties of undefined (reading ' otherwise')
    at Object.recognize (...\node_modules\wink-nlp\src\automaton.js:408:26)

Here's an example of a string I'm using in a pattern that causes this:

'at night - the scn tells the brain to make more melatonin so you get drowsy'

**Comment by rachnachakraborty** [comment]
Hi @markhoney 

Thanks for reaching out to us.

In order to replicate the issue on JS, request you to share your code snippet with sample data.

Best,
Rachna

**Comment by sanjayaksaxena** [comment]
Hi @markhoney please feel free to reopen, closing it for now.
