### ISSUE TITLE
Typescript Types are not accurate

### ISSUE THREAD

**Issue by ali-habibzadeh** [winkjs/wink-nlp#136]
it seems docs says we should use the embeddings like this:

```typescript
import wink from "wink-nlp";
import model from "wink-eng-lite-web-model";
import vectors from "wink-embeddings-sg-100d";

const nlp = wink(model, [], vectors);
```

But in the types wink doesn't take a 3rd argument:
```typescript
wink(theModel: Model, pipe?: string[] | undefined): WinkMethods
```

but I can see its correct in code, but due to the clash we can't use this in Typescript
```typescript
var nlp = function ( theModel, pipe = null, wordEmbeddings = null ) {
```

Additionally, most JS examples online do not match the types provided.

**Comment by rachnachakraborty** [comment]
Hi @ali-habibzadeh,

Thank you so much for highlighting the issue along with details. We've confirmed the TypeScript type inconsistency — an accidental miss. A fix is underway, and we'll update this issue with the progress. We're also improving our processes to prevent similar issues in the future.

Thank you once again for your contribution.

Best,
Rachna

**Comment by sanjayaksaxena** [comment]
Hi @ali-habibzadeh 

Is it possible to also share the JS examples online do not match the types provided?

Best,
Sanjaya
