### ISSUE TITLE
Custom entities, POS and disambiguating

### ISSUE THREAD

**Issue by danielepolencic** [winkjs/wink-nlp#25]
Consider the following phrase:

"This afternoon I plan to go to the bookstore and buy a book on Go".

In the example, go is used as a verb and as a noun (programming language).

I'd like to detect the programming language `Go`. I noticed that when I tag the phrase with POS, the first go is tagged as VB and the second as NNP.

Is there a way to say to the `learnCustomEntities` method that I'm interested to detect the word Go but only when it's an NNP?

```js
const text = 'This afternoon I plan to go to the bookstore and buy a book on Go.';
const patterns = [
  { name: 'go', patterns: [ 'Go&NNP' ] },
];
nlp.learnCustomEntities(patterns);
```

**Comment by rachnachakraborty** [comment]
Hi @danielepolencic,

This construct `{ name: 'go', patterns: [ 'Go&NNP' ] }` is not available here. 

You may use the token value or UPOS in the pattern itself.

```
const text = 'This afternoon I plan to go to the bookstore and buy a book on Go and C Sharp.';
const patterns = [
  { name: 'language', patterns: [ 'Go' ] },
  { name: 'language', patterns: [ 'C Sharp' ] }
];
nlp.learnCustomEntities( patterns, {
  matchValue: true,
  usePOS: false,
  useEntity: false
}  );
```
Runkit output for the above code is as follows:

![image](https://user-images.githubusercontent.com/45709/111152868-3e8efe00-85b7-11eb-8e29-0724e095860e.png)


Please refer to [learnCustomEntities](https://winkjs.org/wink-nlp/learn-custom-entities.html).

Cheers!
Rachna

**Comment by danielepolencic** [comment]
Thanks
