### ISSUE TITLE
readDoc() breaks with long string of numbers

### ISSUE THREAD

**Issue by pburrows** [winkjs/wink-nlp#37]
While parsing some text found in the wild, I noticed winkjs will break when parsing a long string of comma-separated numbers.
No error is thrown, winkNlp simply never returns from the .readDoc call

Here is code that breaks:

```
const text = '47,47,32,67,111,112,121,114,105,103,104,116,32,74,111,121,101,110,116,44,32,73,110,99,46,32,97,110,100,32, '
const nlp = winkNlp(model, []);
const doc = nlp.readDoc(text.toLowerCase());
```

The same code with a long string has no issue:

```
const text = 'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz'
const nlp = winkNlp(model, []);
const doc = nlp.readDoc(text.toLowerCase());
```

**Comment by sanjayaksaxena** [comment]
Thanks for highlighting the issue. Are you using the `wink-eng-lite-web-model` or `wink-eng-lite-model`? Currently there is a bug in wink-eng-lite-model`, which is causing this issue — it will be fixed soon & a patch will be released.

In the mean time consider using `wink-eng-lite-web-model`.

**Comment by sanjayaksaxena** [comment]
Please use Version 1.2.1 July 15, 2021 of `wink-eng-lite-web-model` or Version 1.3.1 July 15, 2021 of 
`wink-eng-lite-model`. This bug was there in the earlier versions of the models.

**Comment by sanjayaksaxena** [comment]
Here is the working code on RunKit: https://runkit.com/sanjaya/60c58d5da950c1001a1426f1 —

<img width="957" alt="image" src="https://user-images.githubusercontent.com/29990/128505785-fbc81868-26b4-4d91-8445-b2da8b3a1d5f.png">

**Comment by pburrows** [comment]
Hey @sanjayaksaxena , thanks for replying so fast. Yes, I am using the light model. I will try the updated version of the model right now.

**Comment by pburrows** [comment]
Can confirm, the 1.3.1 version fixed the issue.
