### ISSUE TITLE
Typescript support missing for `wink-eng-lite-model`

### ISSUE THREAD

**Issue by searleser97** [winkjs/wink-nlp#54]
can't import model using typescript

![image](https://user-images.githubusercontent.com/5056411/134254199-059b12a6-098e-4afc-aabc-bd63a37352d3.png)

**Comment by sanjayaksaxena** [comment]
Please use [`wink-eng-lite-web-model`](https://www.npmjs.com/package/wink-eng-lite-web-model) instead of `wink-eng-lite-model`.

**Comment by searleser97** [comment]
![image](https://user-images.githubusercontent.com/5056411/134347212-11211314-7199-4ca9-be0d-68319a31f708.png)

I am not able to install that model it says that there is just one available

**Comment by searleser97** [comment]
![image](https://user-images.githubusercontent.com/5056411/134348007-26898271-48fb-42d9-9b4d-cb044c629c7b.png)

**Comment by searleser97** [comment]
![image](https://user-images.githubusercontent.com/5056411/134348113-b12ff271-bf6d-4b4a-ba93-80f54e8e34be.png)

**Comment by sanjayaksaxena** [comment]
Use following please:

```sh
# Install wink-nlp
npm install wink-nlp --save
# Install wink-eng-lite-web-model
npm install wink-eng-lite-web-model --save
```

As mentioned in [wink-eng-lite-web-model](https://github.com/winkjs/wink-eng-lite-web-model#getting-started) and [How to install for Web Browser](https://github.com/winkjs/wink-nlp#how-to-install-for-web-browser).

**Comment by searleser97** [comment]
it worked although I am not creating a web application, it is a node.js app, basically
a CLI utility
