### ISSUE TITLE
Custom entity Matching sequence not working

### ISSUE THREAD

**Issue by LorsK** [winkjs/wink-nlp#56]
```
  var text = `Go grocery shopping on Sept 21st`;
   
  const patterns = [
    { name: 'TEST', patterns: ['[CARDINAL|ORDINAL] Sept [CARDINAL|ORDINAL]'] },
  ];
  nlp.learnCustomEntities( patterns );

  var doc = nlp.readDoc(text);
```

When creating a pattern that contains CARDINAL or ORDINAL, it prioritizes the CARDINAL/ORDINAL over the custom entity. In this example the output is `{value: '21st', type: 'ORDINAL'}`  instead of the intended `{value: 'Sept 21st', type: 'TEST'}`

I get this anytime I make any pattern with Cardinal or Ordinal in it. 

NOTE: in this particular issue I am not sure why Sept isn't getting picked up as a Date in the first place, only Sep short form works even though in many places Sept is also used. Which is the main reason I am trying to work around it and create a custom pattern

**Comment by sanjayaksaxena** [comment]
Thanks for spotting the training miss — it is not able to recognize `Sept`. We will train and release a new model, but it will take some time.

The workaround code above to detect the same via custom entities has a small typo mistake. Here is the working code for your reference:

```javascript
const winkNLP = require( 'wink-nlp' );
const its = require( 'wink-nlp/src/its.js' );
const model = require( 'wink-eng-lite-web-model' );
const nlp = winkNLP( model );

var text = `Go grocery shopping on Sept 21st or 1st Sept 2025!`;
   
const patterns = [
  // Added a preceding "|" in the first pattern to allow null prior to Sept 
  { name: 'TEST', patterns: [ '[|CARDINAL|ORDINAL] [Sept] [CARDINAL|ORDINAL]' ] },
];

nlp.learnCustomEntities( patterns );

var doc = nlp.readDoc(text);

console.log(doc.entities().out());
// -> ["21st", "1st", "2025"]
console.log(doc.customEntities().out());
// -> ["Sept 21st", "1st Sept 2025"]
```

**Comment by LorsK** [comment]
That worked, thanks! Will use the workaround until the model is updated :)

**Comment by sanjayaksaxena** [comment]
Closing the issue and will update in this thread when revised model is published.
