### ISSUE TITLE
Trouble using the word "day" in customEntities pattern

### ISSUE THREAD

**Issue by kolakolakola** [winkjs/wink-nlp#76]
I'm trying to use learnCustomEntities to match various patterns. It's working great for most of them, but for some reason I'm having trouble with it picking up the word "day". Here's a sample brief sample:

```
const types = [
{ name: 'today', patterns: [ 'day', 'day is it', 'have the date', 'day it is'] },
{ name: 'where', patterns: [ 'wheres', 'where', 'get to','find', 'place' ] },
];

nlp.learnCustomEntities( types, {matchValue: false, usePOS: true, useEntity: true } );
const doc = nlp.readDoc( text );
const type = doc.customEntities().out( its.detail );
```

A text string like "how do you get to the taco shop" returns "where", but a text string like "what day is it" returns nothing - it seems like none of the phrases including the word "day" get picked up.

Any thoughts? Am I doing something wrong here?

**Comment by rachnachakraborty** [comment]
Hey @kolakolakola 

Since `Day` is an Entity, the `useEntity` flag should be set to `false` for detecting day as part of the pattern.

```
const winkNLP = require( 'wink-nlp' );
const its = require( 'wink-nlp/src/its.js' );
// Use web model for RunKit.
const model = require( 'wink-eng-lite-web-model' );
const nlp = winkNLP( model );

const text = 'how do you get to the taco shop? what day is it?';

const types = [
{ name: 'today', patterns: [ 'day', 'day is it', 'have the date', 'day it is'] },
{ name: 'where', patterns: [ 'wheres', 'where', 'get to','find', 'place' ] },
];

nlp.learnCustomEntities( types, {matchValue: false, usePOS: true, useEntity: false } );
const doc = nlp.readDoc( text );
const type = doc.customEntities().out( its.detail );
```
**Output**

![telegram-cloud-photo-size-5-6215009877554736836-y](https://user-images.githubusercontent.com/45709/161363637-fc8e427a-d7c9-4e28-bf3e-a91eaac31b7c.jpg)

Hope this works for you.

Cheers,
Rachna

**Comment by kolakolakola** [comment]
Amazing, that did the trick - thank you for the quick support!
