### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by labs20** [winkjs/wink-nlp#9]
The following test is failing:
```
const winkNLP = require('wink-nlp')
    , model = require('wink-eng-lite-model')
    , nlp = winkNLP(model)
;
let en_text = 'Dear Sonia, good morning! For elaboration I ask the following information: As for the admission I clarify: There is no device'
    , doc = nlp.readDoc(en_text)
;
console.log(doc.sentences().out());
console.log(doc.entities().out());
console.log(doc.tokens().out());
```

With the error:
```
/Volumes/Work/Developer/Web/rdr_playground/node_modules/wink-eng-lite-model/src/pos-updater.js:1
var updater=function(a,b,c){var d=b.cache;for(let e=0;e<a.length;e+=1){const f=a[e][2],g=a[e][0];0>f?c[g]=Math.abs(f):d.isMemberPOS(b.tokens[4*g],f)&&(c[g]=f)}};module.exports=updater;
                                                                                                                        ^

TypeError: Cannot read property 'isMemberPOS' of undefined
    at updater (/Volumes/Work/Developer/Web/rdr_playground/node_modules/wink-eng-lite-model/src/pos-updater.js:1:121)
    at Object.readDoc (/Volumes/Work/Developer/Web/rdr_playground/node_modules/wink-nlp/src/wink-nlp.js:272:7)
    at Object.<anonymous> (/Volumes/Work/Developer/Web/rdr_playground/test.js:17:17)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by sanjayaksaxena** [comment]
Hello @labs20 

Many thanks for highlighting the issue. 

This has occurred due to incorrect documentation — it mentions an older language model version for installation.

Please use the following command to install the latest model:

```
npm install https://github.com/winkjs/wink-eng-lite-model/releases/download/0.2.0/wink-eng-lite-model-0.2.0.tgz --save
```

Note, documentation is still work in progress.

Your issue has prompted us to improve the language model's installation process significantly, which we will be releasing shortly.

Thanks again for the help.

Best,
Sanjaya

**Comment by labs20** [comment]
Glad to help!

I'm very interested in this lib, its looking quite good.

My main language of interest is brazilian portuguese. Can I hope for a model for that?

Thanks!

**Comment by sanjayaksaxena** [comment]
Thank you for the kind words.

We have plans to release language models for multiple languages.

Even with the current language model, many features should work for you — some examples are tokenization, custom entities, pattern matching,  number of `.out()` options, `.markup()` for text visualization, etc. Sentence boundary detection may work partially. NER & POS tagging will not work.

Will take up the discussion on brazilian portuguese model under the issue #8 that you have raised. Closing this issue.

Best,
Sanjaya

**Comment by rachnachakraborty** [comment]
Hi @labs20 

We plan to initiate discussions on the language model for Portuguese and shall be in touch. 

Did you get a chance to test current language model with Brazilian Portuguese content? 

Your inputs would be useful to us.

Best,
Rachna

**Comment by labs20** [comment]
Hi. I'm still doing some tests on other stuff, but planing to dive into it soon, probably next week.

Will be my pleasure to help. 

Let me know how.
